### ISSUE TITLE
Cannot get bundler to run on fork

### ISSUE THREAD

**Issue by peterwake** [bernat/best_in_place#531]
I can't get my forked copy to run, I get the following:
```
$ bundle
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rails-assets.org/..
Fetching additional metadata from https://rubygems.org/..
Fetching additional metadata from https://rails-assets.org/..
Resolving dependencies...
Using rake 10.5.0
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.4
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.5.1
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.0.0
Using nokogiri 1.6.7.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Using loofah 2.0.3
Using rails-html-sanitizer 1.0.3
Using actionview 4.2.5.1
Using rack 1.6.4
Using rack-test 0.6.3
Using actionpack 4.2.5.1
Using activemodel 4.2.5.1
Using arel 6.0.3
Using activerecord 4.2.5.1
Using addressable 2.4.0
Using bundler 1.6.2
Using thor 0.19.1
Using appraisal 2.1.0
Using railties 4.2.5.1

NoMethodError: undefined method `spec' for nil:NilClass
An error occurred while installing best_in_place (3.1.0), and Bundler cannot continue.
Make sure that `gem install best_in_place -v '3.1.0'` succeeds before bundling.
```
With bundle --verbose it ends with:
```
NoMethodError: undefined method `spec' for nil:NilClass
/Users/pete/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/installer.rb:254:in `spec'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/source/path/installer.rb:19:in `generate_bin'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/source/path.rb:190:in `generate_bin'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/source/path.rb:73:in `install'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/installer.rb:105:in `block in install_gem_from_spec'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/rubygems_integration.rb:162:in `with_build_args'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/installer.rb:104:in `install_gem_from_spec'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/installer.rb:262:in `block in install_sequentially'
/Users/pete/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/forwardable.rb:183:in `each'
/Users/pete/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/forwardable.rb:183:in `each'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/installer.rb:261:in `install_sequentially'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/installer.rb:91:in `run'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/installer.rb:15:in `install'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/cli/install.rb:78:in `run'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/cli.rb:146:in `install'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/vendor/thor/command.rb:27:in `run'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/vendor/thor.rb:363:in `dispatch'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/vendor/thor/base.rb:440:in `start'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/cli.rb:9:in `start'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/bin/bundle:20:in `block in <top (required)>'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
/Users/pete/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/bin/bundle:20:in `<top (required)>'
/Users/pete/.rvm/gems/ruby-2.1.2@global/bin/bundle:23:in `load'
/Users/pete/.rvm/gems/ruby-2.1.2@global/bin/bundle:23:in `<main>'
/Users/pete/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/pete/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```
ruby -v gives me:
```
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
```

**Comment by seuros** [comment]
seem like you have old version of ruby gems. btw you should upgrade your ruby.
try with 2.1.8 if you don't want to bump major version.

**Comment by peterwake** [comment]
Perfect! For anyone else out there (assuming you use rvm)..

```
$ cd best_in_place/
$ rvm get head
$ rvm list known
$ rvm install 2.3
$ rvm use 2.3.0
$ gem install bundle
$ bundle install
```
