### ISSUE TITLE
bip_select + Capybara = Capybara::NotSupportedByDriverError ?

### ISSUE THREAD

**Issue by duffyjp** [bernat/best_in_place#587]
I'm having trouble with bip_select on Capybara.  

```ruby
it "[update] should process the best_in_place form submission", :js do
  visit financials_fringe_descriptions_path
  bip_select fringe_description, :fringe_rate_name, fringe.to_s
  ...
end
```

Firefox visits the page, but as soon as bip_select executes I get this:

```
     Failure/Error: bip_select fringe_description, :fringe_rate_name, fringe.to_s
     
     Capybara::NotSupportedByDriverError:
       Capybara::Driver::Node#trigger
     # /Users/jpd800/.rvm/gems/ruby-2.3.1/gems/capybara-2.14.3/lib/capybara/driver/node.rb:99:in `trigger'
     # /Users/jpd800/.rvm/gems/ruby-2.3.1/gems/capybara-2.14.3/lib/capybara/node/element.rb:341:in `block in trigger'
     # /Users/jpd800/.rvm/gems/ruby-2.3.1/gems/capybara-2.14.3/lib/capybara/node/base.rb:85:in `synchronize'
     # /Users/jpd800/.rvm/gems/ruby-2.3.1/gems/capybara-2.14.3/lib/capybara/node/element.rb:341:in `trigger'
     # /Users/jpd800/.rvm/gems/ruby-2.3.1/gems/best_in_place-3.1.1/lib/best_in_place/test_helpers.rb:33:in `bip_select'
     # ./spec/features/financials/fringe_descriptions_spec.rb:18:in `block (3 levels) in <top (required)>'

```

I think it's worth noting bip_text works with my setup fine.

best_in_place (3.1.1)
 rspec-rails (3.5.2)
  rails (= 5.0.5)
    capybara (2.14.3)
    jquery-rails (4.3.1)
    jquery-ui-rails (6.0.1)
    rails-jquery-autocomplete (1.0.3)

**Comment by duffyjp** [comment]
I'm pretty sure I figured this out:  PR #588
