### ISSUE TITLE
Rails 6 deprecation warning

### ISSUE THREAD

**Issue by JDrizzy** [bernat/best_in_place#623]
Rails 6 deprecation warning raised:

```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.
```

**Comment by v-kumar** [comment]
Can we please merge this PR, so that we can have a clean logs for rails boot?

Thanks @JDrizzy

**Comment by tgrushkasm** [comment]
Still a problem...

```
=> Rails 6.0.3.2 application starting in development 
=> Run `rails server --help` for more startup options
DEPRECATION WARNING: ActionView::Base instances should be constructed with a lookup context, assignments, and a controller. (called from <main> at /Users/tom/myproject/config/environment.rb:5)
/Users/tom/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/best_in_place-3.1.1/lib/best_in_place/railtie.rb:7:in `new'
  /Users/tom/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/best_in_place-3.1.1/lib/best_in_place/railtie.rb:7:in `block in <class:Railtie>'
  /Users/tom/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
```

**Comment by mmotherwell** [comment]
I think this can be closed now. The merged PR fixed it no?

**Comment by favechua** [comment]
Still happening, when is this [PR](https://github.com/bernat/best_in_place/pull/624) gonna merge?
<img width="809" alt="Screenshot 2022-12-23 at 4 28 14 PM" src="https://user-images.githubusercontent.com/89003014/209300896-8beedf2a-e11d-42a6-923f-7d68523b5ee8.png">
